language: r
cache: packages

r_packages:
  - covr

r_github_packages:
  - r-lib/pkgdown

after_success:
  - Rscript -e "pkgdown::build_site(preview = FALSE)"
  - Rscript -e 'library(covr); codecov()'

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
